import pyautogui as pg
import time as tm
import pyperclip
pg.PAUSE = 2
resposta = str(input("Deseja iniciar um curriculo? (  )sim (  )nao\n"))
resposta= resposta.upper()
if resposta== "SIM":
    print("vamos lá!")
    sexo= str(input('Homem ou mulher:'))
    nascimento= str(input("Data de nascimento: xx/xx/xxxx"))
    nome= str(input("SEU NOME:"))
    endereco = str(input("SEU endereço:"))
    telefone = str(input("SEU numero para contato:"))
    email= str(input('Endereço de email: '))
    formacao= str(input("Formação: "))
    ask = str(input('Possui curso?'))
    if ask == 'sim':
        cursos = list()
        local = list()
        while True:
            nome_curso = input("nome do curso: ")
            nome_local = input("nome do local: ")
            p = input("deseja finalizar? sim ou nao")
            cursos.append(nome_curso)
            local.append(nome_local)
            if p == "sim":
                break
    empresa=str(input("Empresa: "))
    funcao = str(input("Função: "))
    periodo = str(input("Periodo: xx/xx/xxxx a xx/xx/xxxx "))
    pg.hotkey('win')
    tm.sleep(3)
    pg.write('explorador de arquivos')
    tm.sleep(2)
    pg.press('enter')
    tm.sleep(2)
    pg.click(x = 1669, y = 142)
    pg.write('curriculo modelo py')
    pg.press('enter')
    tm.sleep(4)
    pg.click(x=757, y=191, clicks=2)
    pg.click(x=786, y=436, clicks=4)
    tm.sleep(4)
    pg.hotkey('ctrl', 'e')
    pg.hotkey('ctrl','n')
    pg.write(nome)
    pg.hotkey('ctrl', 'n')
    pg.press('enter')
    tm.sleep(1)
    if sexo == "mulher":
        pg.write("Brasileira, solteira, nascida em ")
        pg.write(nascimento)
        pg.press('enter')
    else:
        pg.write("Brasileiro, solteiro, nascido em ")
        pg.write(nascimento)
        pg.press('enter')
    pg.write(endereco)
    pg.press('enter')
    pg.write(telefone)
    pg.press('enter')
    pg.write(email)
    pg.press('enter')
    pg.hotkey('ctrl', 'e')
    pg.hotkey('ctrl', 'n')
    pg.write('Formação')
    pg.hotkey('ctrl', 'n')
    pg.press('enter')
    pg.write(formacao)
    pg.press('enter')
    pg.hotkey('ctrl', 'n')
    pg.write('Cursos')
    pg.hotkey('ctrl', 'n')
    pg.press('enter')
    for curso, loc in zip(cursos, local):
        pg.write(curso)
        pg.write(" \n")
        pg.write(loc)
        pg.write(" \n")
    pg.press('enter')
    pg.hotkey('ctrl', 'n')
    pg.write('experiencias profissionais')
    pg.hotkey('ctrl', 'n')
    pg.press('enter')
    pg.write('Empresa: ')
    pg.write(empresa)
    pg.press('enter')
    pg.write('Função: ')
    pg.write(funcao)
    pg.press('enter')
    pg.write('Periodo: ')
    pg.write(periodo)
    tm.sleep(4)
    pg.click(x=20, y=74)
    pg.click(x=78, y=410)
    pg.click(x=811, y=184)
    pg.write(nome)
    pg.click(x=1247, y=214)
    pg.click(x=741, y=383)
    pg.click(x=1535, y=206)
else:
    print("encerrando...")